-- =============================================================================
-- Script DDL para o banco de dados da FarmTech Solutions
-- =============================================================================

-- ========= Limpeza opcional =========
/*
DROP TABLE LeituraSensor CASCADE CONSTRAINTS;
DROP TABLE AjusteAplicacao CASCADE CONSTRAINTS;
DROP TABLE SugestaoSistema CASCADE CONSTRAINTS;
DROP TABLE Sensor CASCADE CONSTRAINTS;
DROP TABLE HistoricoPlantio CASCADE CONSTRAINTS;
DROP TABLE AreaCultivo CASCADE CONSTRAINTS;
DROP TABLE Cultura CASCADE CONSTRAINTS;
*/

-- ========================== Criação das Tabelas ==========================

-- Tabela AreaCultivo: Onde as culturas são plantadas e os sensores instalados.
CREATE TABLE AreaCultivo (
    ID_AreaCultivo NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nome_Area      VARCHAR2(255) NOT NULL,
    Localizacao    VARCHAR2(255),
    Tamanho        NUMBER(10, 2)
);

-- Tabela Cultura: Tipos de plantas cultivadas e seus parâmetros ideais.
CREATE TABLE Cultura (
    ID_Cultura                NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nome_Cultura              VARCHAR2(255) NOT NULL,
    Descricao                 VARCHAR2(500),
    Nivel_Ideal_Umidade_Min   NUMBER(5, 2),
    Nivel_Ideal_Umidade_Max   NUMBER(5, 2),
    Nivel_Ideal_pH_Min        NUMBER(5, 2),
    Nivel_Ideal_pH_Max        NUMBER(5, 2),
    Nivel_Ideal_P_Min         NUMBER(8, 2),
    Nivel_Ideal_P_Max         NUMBER(8, 2),
    Nivel_Ideal_K_Min         NUMBER(8, 2),
    Nivel_Ideal_K_Max         NUMBER(8, 2)
);

-- Tabela Sensor: Dispositivos que coletam dados nas áreas de cultivo.
CREATE TABLE Sensor (
    ID_Sensor        NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Tipo_Sensor      VARCHAR2(15) NOT NULL, 
    Modelo           VARCHAR2(50),
    Data_Instalacao  DATE,
    Status           VARCHAR2(15) NOT NULL,
    ID_AreaCultivo   NUMBER(10) NOT NULL
);

-- Tabela LeituraSensor: Dados coletados pelos sensores ao longo do tempo.
CREATE TABLE LeituraSensor (
    ID_Leitura        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    DataHora_Leitura  TIMESTAMP NOT NULL,
    Valor_Lido        NUMBER(10, 3) NOT NULL,
    ID_Sensor         NUMBER(10) NOT NULL
);

-- Tabela SugestaoSistema: Recomendações geradas pelo sistema.
CREATE TABLE SugestaoSistema (
    ID_Sugestao         NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DataHora_Geracao    TIMESTAMP NOT NULL,
    Tipo_Sugestao       VARCHAR2(50) NOT NULL,
    Detalhes_Sugestao   VARCHAR2(200),
    Status_Sugestao     VARCHAR2(15) NOT NULL,
    ID_AreaCultivo      NUMBER(10) NOT NULL
);

-- Tabela AjusteAplicacao: Ações realizadas (irrigação, nutrientes).
CREATE TABLE AjusteAplicacao (
    ID_Ajuste             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DataHora_Ajuste       TIMESTAMP NOT NULL,
    Tipo_Ajuste           VARCHAR2(15) NOT NULL,
    Quantidade_Aplicada   NUMBER(10, 2) NOT NULL,
    Unidade_Medida        VARCHAR2(10) NOT NULL,
    ID_AreaCultivo        NUMBER(10) NOT NULL,
    ID_Sugestao_Origem    NUMBER(10)
);

-- Tabela HistoricoPlantio: Associa Areas de Cultivo com Culturas ao longo do tempo (N:M).
CREATE TABLE HistoricoPlantio (
    ID_HistoricoPlantio NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Data_Inicio_Plantio DATE NOT NULL,
    Data_Fim_Plantio    DATE,
    ID_AreaCultivo      NUMBER(10) NOT NULL,
    ID_Cultura          NUMBER(10) NOT NULL
);

-- ================== Definição das Chaves Estrangeiras (FK) =================

-- Sensor (N) <-> AreaCultivo (1)
ALTER TABLE Sensor ADD CONSTRAINT fk_sensor_area FOREIGN KEY (ID_AreaCultivo) REFERENCES AreaCultivo (ID_AreaCultivo);

-- LeituraSensor (N) <-> Sensor (1)
ALTER TABLE LeituraSensor ADD CONSTRAINT fk_leitura_sensor FOREIGN KEY (ID_Sensor) REFERENCES Sensor (ID_Sensor) ON DELETE CASCADE; -- Leituras são inúteis sem o sensor

-- SugestaoSistema (N) <-> AreaCultivo (1)
ALTER TABLE SugestaoSistema ADD CONSTRAINT fk_sugestao_area FOREIGN KEY (ID_AreaCultivo) REFERENCES AreaCultivo (ID_AreaCultivo);

-- AjusteAplicacao (N) <-> AreaCultivo (1)
ALTER TABLE AjusteAplicacao ADD CONSTRAINT fk_ajuste_area FOREIGN KEY (ID_AreaCultivo) REFERENCES AreaCultivo (ID_AreaCultivo);

-- AjusteAplicacao (0,N) <-> SugestaoSistema (0,1) - FK opcional
ALTER TABLE AjusteAplicacao ADD CONSTRAINT fk_ajuste_sugestao FOREIGN KEY (ID_Sugestao_Origem) REFERENCES SugestaoSistema (ID_Sugestao) ON DELETE SET NULL; -- Se a sugestão for deletada, o ajuste perde a referência mas continua existindo.

-- HistoricoPlantio (N) <-> AreaCultivo (1)
ALTER TABLE HistoricoPlantio ADD CONSTRAINT fk_hist_area FOREIGN KEY (ID_AreaCultivo) REFERENCES AreaCultivo (ID_AreaCultivo);

-- HistoricoPlantio (N) <-> Cultura (1)
ALTER TABLE HistoricoPlantio ADD CONSTRAINT fk_hist_cultura FOREIGN KEY (ID_Cultura) REFERENCES Cultura (ID_Cultura);

-- ==================== Definição das Constraints de Checagem ====================

ALTER TABLE Sensor ADD CONSTRAINT chk_sensor_tipo CHECK (Tipo_Sensor IN ('Umidade', 'pH', 'Fósforo', 'Potássio'));
ALTER TABLE Sensor ADD CONSTRAINT chk_sensor_status CHECK (Status IN ('Ativo', 'Inativo', 'Manutenção'));

ALTER TABLE SugestaoSistema ADD CONSTRAINT chk_sugestao_status CHECK (Status_Sugestao IN ('Pendente', 'Aplicada', 'Ignorada', 'Cancelada')); -- Adicionei 'Cancelada'

ALTER TABLE AjusteAplicacao ADD CONSTRAINT chk_ajuste_tipo CHECK (Tipo_Ajuste IN ('Irrigação', 'Nutriente P', 'Nutriente K'));

-- ============================ Fim do Script DDL ============================