-- =============================================================================
-- Script DDL para o banco de dados da FarmTech Solutions
-- =============================================================================

-- ========= Limpeza opcional =========
/*
DROP TABLE LeituraSensor CASCADE;
DROP TABLE AjusteAplicacao CASCADE;
DROP TABLE SugestaoSistema CASCADE;
DROP TABLE Sensor CASCADE;
DROP TABLE HistoricoPlantio CASCADE;
DROP TABLE AreaCultivo CASCADE;
DROP TABLE Cultura CASCADE;
*/

-- ========================== Criação das Tabelas ==========================

-- Tabela AreaCultivo: Onde as culturas são plantadas e os sensores instalados.
CREATE TABLE AreaCultivo (
    ID_AreaCultivo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nome_Area      VARCHAR(255) NOT NULL,
    Localizacao    VARCHAR(255),
    Tamanho        NUMERIC(10, 2)
);

-- Tabela Cultura: Tipos de plantas cultivadas e seus parâmetros ideais.
CREATE TABLE Cultura (
    ID_Cultura                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nome_Cultura              VARCHAR(255) NOT NULL,
    Descricao                 VARCHAR(500),
    Nivel_Ideal_Umidade_Min   NUMERIC(5, 2),
    Nivel_Ideal_Umidade_Max   NUMERIC(5, 2),
    Nivel_Ideal_pH_Min        NUMERIC(5, 2),
    Nivel_Ideal_pH_Max        NUMERIC(5, 2),
    Nivel_Ideal_P_Min         NUMERIC(8, 2),
    Nivel_Ideal_P_Max         NUMERIC(8, 2),
    Nivel_Ideal_K_Min         NUMERIC(8, 2),
    Nivel_Ideal_K_Max         NUMERIC(8, 2)
);

-- Tabela Sensor: Dispositivos que coletam dados nas áreas de cultivo.
CREATE TABLE Sensor (
    ID_Sensor        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Tipo_Sensor      VARCHAR(15) NOT NULL, 
    Modelo           VARCHAR(50),
    Data_Instalacao  DATE,
    Status           VARCHAR(15) NOT NULL,
    ID_AreaCultivo   INTEGER NOT NULL
);

-- Tabela LeituraSensor: Dados coletados pelos sensores ao longo do tempo.
CREATE TABLE LeituraSensor (
    ID_Leitura        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    DataHora_Leitura  TIMESTAMP NOT NULL,
    Valor_Lido        NUMERIC(10, 3) NOT NULL,
    ID_Sensor         INTEGER NOT NULL
);

-- Tabela SugestaoSistema: Recomendações geradas pelo sistema.
CREATE TABLE SugestaoSistema (
    ID_Sugestao         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DataHora_Geracao    TIMESTAMP NOT NULL,
    Tipo_Sugestao       VARCHAR(50) NOT NULL,
    Detalhes_Sugestao   VARCHAR(200),
    Status_Sugestao     VARCHAR(15) NOT NULL,
    ID_AreaCultivo      INTEGER NOT NULL
);

-- Tabela AjusteAplicacao: Ações realizadas (irrigação, nutrientes).
CREATE TABLE AjusteAplicacao (
    ID_Ajuste             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DataHora_Ajuste       TIMESTAMP NOT NULL,
    Tipo_Ajuste           VARCHAR(15) NOT NULL,
    Quantidade_Aplicada   NUMERIC(10, 2) NOT NULL,
    Unidade_Medida        VARCHAR(10) NOT NULL,
    ID_AreaCultivo        INTEGER NOT NULL,
    ID_Sugestao_Origem    INTEGER
);

-- Tabela HistoricoPlantio: Associa Areas de Cultivo com Culturas ao longo do tempo (N:M).
CREATE TABLE HistoricoPlantio (
    ID_HistoricoPlantio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Data_Inicio_Plantio DATE NOT NULL,
    Data_Fim_Plantio    DATE,
    ID_AreaCultivo      INTEGER NOT NULL,
    ID_Cultura          INTEGER NOT NULL
);

-- ================== Definição das Chaves Estrangeiras (FK) =================

-- Sensor (N) <-> AreaCultivo (1)
ALTER TABLE Sensor ADD CONSTRAINT fk_sensor_area FOREIGN KEY (ID_AreaCultivo) REFERENCES AreaCultivo (ID_AreaCultivo);

-- LeituraSensor (N) <-> Sensor (1)
ALTER TABLE LeituraSensor ADD CONSTRAINT fk_leitura_sensor FOREIGN KEY (ID_Sensor) REFERENCES Sensor (ID_Sensor) ON DELETE CASCADE; -- Leituras são inúteis sem o sensor

-- SugestaoSistema (N) <-> AreaCultivo (1)
ALTER TABLE SugestaoSistema ADD CONSTRAINT fk_sugestao_area FOREIGN KEY (ID_AreaCultivo) REFERENCES AreaCultivo (ID_AreaCultivo);

-- AjusteAplicacao (N) <-> AreaCultivo (1)
ALTER TABLE AjusteAplicacao ADD CONSTRAINT fk_ajuste_area FOREIGN KEY (ID_AreaCultivo) REFERENCES AreaCultivo (ID_AreaCultivo);

-- AjusteAplicacao (0,N) <-> SugestaoSistema (0,1) - FK opcional
ALTER TABLE AjusteAplicacao ADD CONSTRAINT fk_ajuste_sugestao FOREIGN KEY (ID_Sugestao_Origem) REFERENCES SugestaoSistema (ID_Sugestao) ON DELETE SET NULL; -- Se a sugestão for deletada, o ajuste perde a referência mas continua existindo.

-- HistoricoPlantio (N) <-> AreaCultivo (1)
ALTER TABLE HistoricoPlantio ADD CONSTRAINT fk_hist_area FOREIGN KEY (ID_AreaCultivo) REFERENCES AreaCultivo (ID_AreaCultivo);

-- HistoricoPlantio (N) <-> Cultura (1)
ALTER TABLE HistoricoPlantio ADD CONSTRAINT fk_hist_cultura FOREIGN KEY (ID_Cultura) REFERENCES Cultura (ID_Cultura);

-- ==================== Definição das Constraints de Checagem ====================

ALTER TABLE Sensor ADD CONSTRAINT chk_sensor_tipo CHECK (Tipo_Sensor IN ('Umidade', 'pH', 'Fósforo', 'Potássio'));
ALTER TABLE Sensor ADD CONSTRAINT chk_sensor_status CHECK (Status IN ('Ativo', 'Inativo', 'Manutenção'));

ALTER TABLE SugestaoSistema ADD CONSTRAINT chk_sugestao_status CHECK (Status_Sugestao IN ('Pendente', 'Aplicada', 'Ignorada', 'Cancelada')); -- Adicionei 'Cancelada'

ALTER TABLE AjusteAplicacao ADD CONSTRAINT chk_ajuste_tipo CHECK (Tipo_Ajuste IN ('Irrigação', 'Nutriente P', 'Nutriente K'));

-- ============================ Fim do Script DDL ============================